In [6]:
import numpy as np
a = np.array([[0,1,2],[3,4,5]])

In [11]:
a[:,0]=[2,2]

In [12]:
a[:,0]


array([2, 2])

In [15]:
b = np.array([1,2,3,4])
c,d=np.split(b,2)
a[:,0] = c

In [23]:
np.concatenate((np.array([1,2,4]), np.array([3,4,5]) ))

array([1, 2, 4, 3, 4, 5])

In [5]:
from scipy.integrate import solve_ivp
def exponential_decay(t, y): return -0.5 * y
sol = solve_ivp(exponential_decay, [0, 10], [2, 4, 8],
                t_eval=[0, 1, 2, 4, 10])
print(sol['y'])

[[2.         4.         8.        ]
 [1.21305369 2.42610739 4.85221478]
 [0.73534021 1.47068043 2.94136085]
 [0.27069123 0.54138247 1.08276494]
 [0.01350781 0.02701561 0.05403123]]
