In [58]:
import autograd
import autograd.numpy as np

import scipy.integrate
solve_ivp = scipy.integrate.solve_ivp
m1 =  1.0
m2 = 1.0
l1 = 1.0
l2 = 1.0
g = 9.8
state = np.array([1.57, 1.57, 0., 0.])

def hamiltonian_fn(coords):
    state = coords
    H = (m2*(l2*state[2])**2+ (m1+m2)*(l1*state[3])**2- 2*m2*l1*l2*state[2]*state[3]*np.cos(state[0]-state[1]))/(2*m2*((l1*l2)**2)*(m1+m2*(np.sin(state[0]-state[1]))**2))\
        -(m1+m2)*g*l1*np.cos(state[0])-m2*g*l2*np.cos(state[1])
    return H

def dynamics_fn(t, coords):
    dcoords = autograd.grad(hamiltonian_fn)(coords)

    dqdt, dpdt = dcoords[2:],-dcoords[0:2]
    S = np.concatenate([dqdt,dpdt],axis=-1)
    return S
hamiltonian_fn(state)
dynamics_fn(0,state)


[19.59999379  9.79999689  0.          0.        ]


array([  0.        ,   0.        , -19.59999379,  -9.79999689])

In [20]:
a=np.array([[1,2],[3,4]])
b = np.array([1,2])
c = np.array([3,4])
np.concatenate((b,c),axis=-1)

array([1, 2, 3, 4])

In [41]:
def hamiltonian_fnp(coords):
    q, p = np.split(coords,2)
    H = 3*(1-np.cos(q)) + p**2 # pendulum hamiltonian
    print(H)
    return H

def dynamics_fnp(t, coords):
    dcoords = autograd.grad(hamiltonian_fnp)(coords)
    print(dcoords)
    dqdt, dpdt = np.split(dcoords,2)
    S = np.concatenate([dpdt, -dqdt], axis=-1)
    return S

In [43]:
y0 = np.array([1.57,0.])
dynamics_fnp(None, y0)

Autograd ArrayBox with value [2.99761102]
[2.99999905 0.        ]


array([ 0.        , -2.99999905])